sudo: false
language: python
arch:
  - AMD64
  - ppc64le
python:
  - 3.6
  - 3.5
cache: pip
env:
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning
    - PYTHONASYNCIODEBUG=1
matrix:
  fast_finish: true
  include:
    - { python: "3.7", dist: xenial, sudo: true }
    - { python: "3.7", dist: xenial, sudo: true, arch: ppc64le }
install:
  - pip install flake8 coverage sphinx -e .
script:
  - flake8
  - python -m unittest discover tests
  - (cd docs && sphinx-build -n -W . _build)
after_success:
  - coverage report
deploy:
  provider: pypi
  user: etianen
  password:
    secure: X9E2HsOMOSmLcH0br9LlNy8EI7AYEf7lGKM2gCOgxWYd7M9i3rL9nPT8JJWzilQgCigjQ3L9q5wTSvp5LxxOVqCQgIUktTKXuIEJgWKcF6kKnq8usFETeXLAIAf4J0BnyGHK7pWTPA0ocZv4wmVfOEVymzwogbWT4uSs1vhFSRQ=
  on:
    tags: true
    python: 3.6
    repo: etianen/aiohttp-wsgi
  distributions: sdist bdist_wheel
notifications:
  email: false
